# Torch Datatypes:

* it has maily one data that is number and this numbers are also classify into two types
  *    1. int   - 16-bit, 32-bit, 64-bit       ------> 64 default
       2. float - 16-bit, 32-bit, 64-bit       ------> 32 default

* default datatype of torch is float32

In [1]:
import torch

In [2]:
sample = torch.rand(size=(3,4))
sample

tensor([[0.3788, 0.4013, 0.8681, 0.9853],
        [0.3695, 0.8887, 0.6797, 0.3463],
        [0.5126, 0.9270, 0.7235, 0.9826]])

In [4]:
sample.dtype

torch.float32

In [10]:
sample_int = torch.arange(1, 10, dtype = int)
sample_int

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
sample_int.dtype

torch.int64

---
## Datatype Changing:
   * some we need to perform some arthmetical operations on tensor that if datatypes are different then it can not perform operations. due to different datatypes

   * 

In [25]:
# default float value:
x = torch.arange(1, 10.)
x, x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

#### float32   --->  float16

In [27]:
# float32 to float16
x_float = x.type(torch.float16)

In [24]:
x_float

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

#### float32  --->  int8

In [28]:
# float32 to int8
x_int8 = x.type(torch.int8)

In [29]:
x_int8

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)

---

# Getting Information from Tensor's :

   * Shape   - checking Size
   * dtype   - Checking Datatype
   * device  - checking where the Tensor is Stored

#### Example-

In [30]:
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8561, 0.5623, 0.6072, 0.7850],
        [0.1332, 0.9163, 0.0855, 0.7430],
        [0.7655, 0.6856, 0.9799, 0.8403]])

In [37]:
some_tensor.shape  # 3X4

torch.Size([3, 4])

In [38]:
some_tensor.dtype   # Float32

torch.float32

In [39]:
some_tensor.device   # CPU

device(type='cpu')