# Some Important Operation for Deep Learning.

   * Rechaping
   * view
   * Stacking
   * Squeezing
   * Unsqueezing
   * Permute
   * indexing
---

In [2]:
import torch

In [3]:
# Sample tensor

tensor = torch.arange(1, 9.)
tensor

tensor([1., 2., 3., 4., 5., 6., 7., 8.])

### 1. Reshape :

In [4]:
reshaped_tensor = tensor.reshape(2, 4)
reshaped_tensor

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])

In [5]:
reshaped_tensor = tensor.reshape(2, 2, 2)
reshaped_tensor

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])

---
### 2. View
   * view is similar to reshape function.
   * but major difference is by using view function we can direct change the values by using index in tensor
   * it changes are permenent in tensor

In [45]:
# sample tesnor
tensor

tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [18]:
y_view = tensor.view(2,4)
y_view

tensor([[10.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]])

In [19]:
y_view[0, 0] = 10

In [20]:
y_view

tensor([[10.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.]])

In [21]:
tensor

tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

---
### 3. Stacking:
   * it can add tensor on tensor (concatinate) if condition is size of all stack required same
   * dim =0 - concatinate with row wise
   * dim =1 - concatinate with columns wise

In [39]:
t1 = torch.arange(1,6, dtype = torch.float32)
t2 = torch.arange(5,10, dtype = torch.float32)
t1, t2

(tensor([1., 2., 3., 4., 5.]), tensor([5., 6., 7., 8., 9.]))

In [42]:
# row size stacking:
torch.stack([t1, t1, t2], dim= 0)

tensor([[1., 2., 3., 4., 5.],
        [1., 2., 3., 4., 5.],
        [5., 6., 7., 8., 9.]])

In [43]:
# Column wise stacking
torch.stack([t1, t1, t2], dim= 1)

tensor([[1., 1., 5.],
        [2., 2., 6.],
        [3., 3., 7.],
        [4., 4., 8.],
        [5., 5., 9.]])

---
### 4. Unsqueezeing

* add new dimension on tensor:

In [46]:
tensor

tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [48]:
tensor.shape, tensor.dim()

(torch.Size([8]), 1)

In [52]:
new_tensor = tensor.unsqueeze(dim= 0)
new_tensor

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.]])

In [54]:
new_tensor.shape, new_tensor.dim()

(torch.Size([1, 8]), 2)

---
### 6. squeezing:

* remove dimension in tensor

In [58]:
new_tensor

tensor([[10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.]])

In [59]:
new_tensor.shape

torch.Size([1, 8])

In [62]:
squeeze = new_tensor.squeeze()
squeeze

tensor([10.,  2.,  3.,  4.,  5.,  6.,  7.,  8.])

In [63]:
squeeze.shape

torch.Size([8])

 ---
### 7. Permute:

* this is used when we want to change position or dimensions

In [66]:
sample_tensor = torch.rand(2, 3, 4)  # positions ( 0, 1, 2)
sample_tensor

tensor([[[0.5547, 0.9508, 0.9743, 0.8106],
         [0.3917, 0.1453, 0.4711, 0.5331],
         [0.9853, 0.2032, 0.1287, 0.4698]],

        [[0.3476, 0.4742, 0.3376, 0.5886],
         [0.0388, 0.7523, 0.7590, 0.1478],
         [0.4824, 0.7596, 0.4329, 0.1579]]])

In [67]:
sample_tensor.shape

torch.Size([2, 3, 4])

In [68]:
# chaninge position
x_permit = sample_tensor.permute(2, 0, 1)
x_permit

tensor([[[0.5547, 0.3917, 0.9853],
         [0.3476, 0.0388, 0.4824]],

        [[0.9508, 0.1453, 0.2032],
         [0.4742, 0.7523, 0.7596]],

        [[0.9743, 0.4711, 0.1287],
         [0.3376, 0.7590, 0.4329]],

        [[0.8106, 0.5331, 0.4698],
         [0.5886, 0.1478, 0.1579]]])

In [70]:
x_permit.shape

torch.Size([4, 2, 3])

In [72]:
# here we can see we have change the positions of dimensions
x_permit.shape, sample_tensor.shape

(torch.Size([4, 2, 3]), torch.Size([2, 3, 4]))

---
### 8. Indexing 

In [76]:
tensor = torch.arange(1, 10)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
tensor= tensor.reshape(1,3, 3)
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [81]:
tensor.shape

torch.Size([1, 3, 3])

In [83]:
# print all values in 1-Dimension
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [89]:
# print all values in first row from first dimension
tensor[0, 0]

tensor([1, 2, 3])

In [90]:
# print all values in 2nd row from first dimension
tensor[0,1]

tensor([4, 5, 6])

In [92]:
# print 3rd value from 2row and one dimension  = 6
tensor[0, 1, 2]

tensor(6)

---
### 9. Reproducibility:  (Random_seed)

* when we run below code every time we get new different value but we want ot create multiple tensors but its value are remain same that time it can use


In [93]:

tensor1 = torch.rand(3, 4)
tensor2 = torch.rand(3, 4)

In [97]:
tensor1

tensor([[0.9571, 0.1891, 0.7343, 0.4606],
        [0.7728, 0.9456, 0.0489, 0.8898],
        [0.7774, 0.2275, 0.6151, 0.0988]])

In [98]:
tensor2

tensor([[0.6768, 0.6139, 0.7276, 0.4038],
        [0.3646, 0.5478, 0.7418, 0.5839],
        [0.0751, 0.9780, 0.8882, 0.3818]])

In [100]:
# Setting Manual Seed: (reproucibility)
torch.manual_seed(5)
tensor1 = torch.rand(3, 4)
tensor1

tensor([[0.8303, 0.1261, 0.9075, 0.8199],
        [0.9201, 0.1166, 0.1644, 0.7379],
        [0.0333, 0.9942, 0.6064, 0.5646]])

* #### now every time we set manual seed data that time always we getting same value in from each newly created tensor

In [101]:
torch.manual_seed(5)
tensor_123 = torch.rand(3,4)
tensor_123

tensor([[0.8303, 0.1261, 0.9075, 0.8199],
        [0.9201, 0.1166, 0.1644, 0.7379],
        [0.0333, 0.9942, 0.6064, 0.5646]])

#### here, we can see the 'tensor1' and 'tensor_123' as same value 

# Runnig code on GPU

In [102]:
torch.cuda.is_available()

False

In [103]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [104]:
torch.cuda.device_count()

0

In [105]:
tensor = torch.tensor([1, 2, 3])

In [106]:
tensor

tensor([1, 2, 3])

In [107]:
tensor.device

device(type='cpu')

In [108]:
tensor_gpu = tensor.to(device)

In [109]:
tensor_gpu.device

device(type='cpu')