# Numpy & Pytorch

* numpy to tensor conversion
* tensor to numpy conversion

In [1]:
import torch 
import numpy as np

In [2]:
data = np.arange(1,10)

In [6]:
data

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

---
### 1. Numpy to Tensor:

In [15]:
tensor = torch.from_numpy(data)

In [20]:
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int32)

In [21]:
tensor.type(torch.int8)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)

---
### 2. Tesnor to Numpy:

In [23]:
arr= tensor.numpy()

In [24]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])