# Running code on GPU


######   Run This code on Google Colab/ device Which contains GPU




###### .

In [1]:
import torch

### 1. checking 'cuda' is available or not

In [3]:
torch.cuda.is_available()

False

### 2. this line is mendatory to write every time

In [5]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

### 3. checking how may GPU Slot are available

In [6]:
torch.cuda.device_count()

0

In [7]:
# Creating tensor:
tensor = torch.tensor([1,2,3,4])
tensor

tensor([1, 2, 3, 4])

---
## Running on GPU

In [15]:
tensor.to(device)

tensor([1, 2, 3, 4])

In [16]:
tensor.device

device(type='cpu')

---
## return back to CPU

In [17]:
gpu_run

tensor([1, 2, 3, 4])

In [18]:
gpu_run.cpu()

tensor([1, 2, 3, 4])